name: FakeOnline
version: 1.0
author: moderator_man
main: me.moderator_man.fo.FakeOnline
commands:
    register:
        description: Register an account
        usage: /register <password> <confirm>
    login:
        description: Login to your account
        usage: /login <password>
    changepassword:
        description: Change your password
        usage: /changepassword <old> <new>
    deleteaccount:
        description: Delete an account
        usage: /deleteaccount <username>
    createaccount:
        description: Create an account
        usage: /createaccount <username> <password>